version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      routine-nuget-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: "/src/RaceHunter.Web"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      routine-web-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: "/tests/RaceHunter.AcceptanceTests"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      routine-acceptance-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      routine-action-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
